site_name: CrystalENVT
theme:
  name: simple-blog
  custom_dir: siteTheme/
  logo: assets/logo.png
  favicon: assets/favicon.ico
  theme_style: dark
  components:
    title: false
    preview: false
    footer: false
extra_css:
  - assets/responsiveCal.css
  - assets/table_fix.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/particlesjs/2.2.1/particles.min.js
markdown_extensions:
  - tables
plugins:
  - search
  - minify_html
  - redirects:
      redirect_maps:
        'discord.md': 'https://discord.gg/7MYgcYn'
        'ko-fi.md': 'https://ko-fi.com/CrystalENVT'
        'kofi.md': 'https://ko-fi.com/CrystalENVT'
        'twitch.md': 'https://twitch.tv/CrystalENVT'
        'youtube.md': 'https://youtube.com/@CrystalENVT'
        'yt.md': 'https://youtube.com/@CrystalENVT'
