name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm .gitignore
      - run: sudo apt-get install -y mkdocs
      - run: mkdocs gh-deploy --force --clean --verbose
